-- Atualizar tabela goals com 27 indicadores como colunas
ALTER TABLE `goals` 
ADD COLUMN `managerId` varchar(64) NOT NULL AFTER `id`,
ADD COLUMN `businessMonth` decimal(15,2) AFTER `year`,
ADD COLUMN `cancelledSales` decimal(15,2) AFTER `businessMonth`,
ADD COLUMN `vsoRatio` decimal(5,2) AFTER `cancelledSales`,
ADD COLUMN `commissionReceived` decimal(15,2) AFTER `vsoRatio`,
ADD COLUMN `commissionSold` decimal(15,2) AFTER `commissionReceived`,
ADD COLUMN `commissionPending` decimal(15,2) AFTER `commissionSold`,
ADD COLUMN `portfolioDisclosure` decimal(15,2) AFTER `commissionPending`,
ADD COLUMN `prospectingMonth` decimal(15,2) AFTER `portfolioDisclosure`,
ADD COLUMN `removalsMonth` decimal(15,2) AFTER `prospectingMonth`,
ADD COLUMN `commissionPercentage` decimal(5,2) AFTER `removalsMonth`,
ADD COLUMN `businessOver1m` decimal(15,2) AFTER `commissionPercentage`,
ADD COLUMN `readyCalls` decimal(15,2) AFTER `businessOver1m`,
ADD COLUMN `launchCalls` decimal(15,2) AFTER `readyCalls`,
ADD COLUMN `avgReceiptTime` decimal(10,2) AFTER `launchCalls`,
ADD COLUMN `cancelledPendingRatio` decimal(5,2) AFTER `avgReceiptTime`,
ADD COLUMN `avgSaleTime` decimal(10,2) AFTER `cancelledPendingRatio`,
ADD COLUMN `avgPropertyValue` decimal(15,2) AFTER `avgSaleTime`,
ADD COLUMN `networkBusiness` decimal(15,2) AFTER `avgPropertyValue`,
ADD COLUMN `internalBusiness` decimal(15,2) AFTER `networkBusiness`,
ADD COLUMN `externalPartnership` decimal(15,2) AFTER `internalBusiness`,
ADD COLUMN `launchBusiness` decimal(15,2) AFTER `externalPartnership`,
ADD COLUMN `generalExpense` decimal(15,2) AFTER `launchBusiness`,
ADD COLUMN `taxExpense` decimal(15,2) AFTER `generalExpense`,
ADD COLUMN `innovationFund` decimal(15,2) AFTER `taxExpense`,
ADD COLUMN `partnersResult` decimal(15,2) AFTER `innovationFund`,
ADD COLUMN `emergencyFund` decimal(15,2) AFTER `partnersResult`,
DROP COLUMN `month`,
DROP COLUMN `teamGoal`;
