CREATE TABLE `historicalSales` (
	`id` varchar(64) NOT NULL,
	`companyId` varchar(64) NOT NULL,
	`propertyReference` varchar(100),
	`propertyAddress` text,
	`propertyNeighborhood` varchar(255),
	`businessType` varchar(100),
	`saleDate` timestamp,
	`acquisitionDate` timestamp,
	`listingPrice` decimal(15,2),
	`salePrice` decimal(15,2),
	`commissionAmount` decimal(15,2),
	`commissionPercentage` decimal(5,2),
	`acquisitionBrokerName` varchar(255),
	`saleBrokerName` varchar(255),
	`acquisitionStore` varchar(100),
	`saleStore` varchar(100),
	`clientSource` varchar(255),
	`paymentMethod` varchar(255),
	`status` varchar(50) DEFAULT 'commission_paid',
	`createdAt` timestamp DEFAULT (now()),
	`updatedAt` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `historicalSales_id` PRIMARY KEY(`id`)
);
