import { mysqlTable, mysqlSchema, AnyMySqlColumn, varchar, mysqlEnum, text, timestamp, decimal, index, int } from "drizzle-orm/mysql-core"
import { sql } from "drizzle-orm"

export const actionLogs = mysqlTable("actionLogs", {
	id: varchar({ length: 64 }).notNull(),
	companyId: varchar({ length: 64 }),
	userId: varchar({ length: 64 }).notNull(),
	targetType: mysqlEnum(['user','company','sale','commission','license']).notNull(),
	targetId: varchar({ length: 64 }),
	action: mysqlEnum(['create','update','delete','activate','deactivate','login','reset_password','block_user','unblock_user','assign_manager','assign_company']).notNull(),
	details: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP'),
});

export const bonuses = mysqlTable("bonuses", {
	id: varchar({ length: 64 }).notNull(),
	companyId: varchar({ length: 64 }).notNull(),
	name: varchar({ length: 255 }).notNull(),
	description: text(),
	bonusValue: decimal({ precision: 15, scale: 2 }),
	bonusPercentage: decimal({ precision: 5, scale: 2 }),
	type: mysqlEnum(['bonificacao','premio','outro']).notNull(),
	linkedTo: mysqlEnum(['referencia','equipe','meta','nenhum']).default('nenhum'),
	linkedValue: varchar({ length: 255 }),
	applicableTo: varchar({ length: 255 }),
	startDate: timestamp({ mode: 'string' }),
	endDate: timestamp({ mode: 'string' }),
	isActive: tinyint().default(1),
	createdBy: varchar({ length: 64 }).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP'),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow(),
});

export const commissionApprovals = mysqlTable("commissionApprovals", {
	id: varchar({ length: 64 }).notNull(),
	commissionId: varchar({ length: 64 }).notNull(),
	saleId: varchar({ length: 64 }).notNull(),
	companyId: varchar({ length: 64 }).notNull(),
	status: mysqlEnum(['proposta','enviado_gerente','aprovado_gerente','enviado_financeiro','aprovado_financeiro','recusado','pago']).default('proposta').notNull(),
	sentToManagerAt: timestamp({ mode: 'string' }),
	approvedByManagerAt: timestamp({ mode: 'string' }),
	approvedByManagerId: varchar({ length: 64 }),
	sentToFinanceAt: timestamp({ mode: 'string' }),
	approvedByFinanceAt: timestamp({ mode: 'string' }),
	approvedByFinanceId: varchar({ length: 64 }),
	paidAt: timestamp({ mode: 'string' }),
	rejectionReason: text(),
	rejectedAt: timestamp({ mode: 'string' }),
	rejectedBy: varchar({ length: 64 }),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP'),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow(),
});

export const commissionHistory = mysqlTable("commissionHistory", {
	id: varchar({ length: 64 }).notNull(),
	commissionId: varchar({ length: 64 }).notNull(),
	previousValue: decimal({ precision: 15, scale: 2 }),
	newValue: decimal({ precision: 15, scale: 2 }).notNull(),
	previousStatus: varchar({ length: 64 }),
	newStatus: varchar({ length: 64 }).notNull(),
	changedBy: varchar({ length: 64 }).notNull(),
	approvedBy: varchar({ length: 64 }),
	approvalDate: timestamp({ mode: 'string' }),
	reason: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP'),
});

export const commissionRules = mysqlTable("commissionRules", {
	id: varchar({ length: 64 }).notNull(),
	companyId: varchar({ length: 64 }).notNull(),
	businessType: varchar({ length: 255 }).notNull(),
	angariadorPercentage: decimal({ precision: 5, scale: 2 }).notNull(),
	vendedorPercentage: decimal({ precision: 5, scale: 2 }).notNull(),
	description: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP'),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow(),
});

export const commissions = mysqlTable("commissions", {
	id: varchar({ length: 64 }).notNull(),
	saleId: varchar({ length: 64 }).notNull(),
	companyId: varchar({ length: 64 }).notNull(),
	brokerId: varchar({ length: 64 }).notNull(),
	commissionValue: decimal({ precision: 15, scale: 2 }).notNull(),
	commissionPercentage: decimal({ precision: 5, scale: 2 }).notNull(),
	type: mysqlEnum(['angariacao','venda','parceria']).notNull(),
	status: mysqlEnum(['pending','received','paid','cancelled']).default('pending').notNull(),
	paymentDate: timestamp({ mode: 'string' }),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP'),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow(),
});

export const companies = mysqlTable("companies", {
	id: varchar({ length: 64 }).notNull(),
	name: varchar({ length: 255 }).notNull(),
	email: varchar({ length: 320 }),
	phone: varchar({ length: 20 }),
	address: text(),
	logo: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP'),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow(),
	licenseType: mysqlEnum(['perpetual','monthly','quarterly','semiannual','annual']).default('monthly'),
	licenseExpiresAt: timestamp({ mode: 'string' }),
	isActive: tinyint().default(1),
	licenseStartDate: timestamp({ mode: 'string' }),
	contractResponsible: varchar({ length: 255 }),
	contractResponsibleEmail: varchar({ length: 320 }),
	contractResponsiblePhone: varchar({ length: 20 }),
	contractStartDate: timestamp({ mode: 'string' }),
	contractNotes: text(),
	totalLogins: int().default(0),
	cnpj: varchar({ length: 20 }),
	notificationEmail: varchar({ length: 320 }),
	tradeName: varchar({ length: 255 }),
},
(table) => [
	index("companies_cnpj_unique").on(table.cnpj),
]);

export const goals = mysqlTable("goals", {
	id: varchar({ length: 64 }).notNull(),
	managerId: varchar({ length: 64 }).notNull(),
	companyId: varchar({ length: 64 }).notNull(),
	year: int().notNull(),
	businessMonth: decimal({ precision: 15, scale: 2 }),
	cancelledSales: decimal({ precision: 15, scale: 2 }),
	vsoRatio: decimal({ precision: 5, scale: 2 }),
	commissionReceived: decimal({ precision: 15, scale: 2 }),
	commissionSold: decimal({ precision: 15, scale: 2 }),
	commissionPending: decimal({ precision: 15, scale: 2 }),
	portfolioDisclosure: decimal({ precision: 15, scale: 2 }),
	prospectingMonth: decimal({ precision: 15, scale: 2 }),
	removalsMonth: decimal({ precision: 15, scale: 2 }),
	commissionPercentage: decimal({ precision: 5, scale: 2 }),
	businessOver1M: decimal({ precision: 15, scale: 2 }),
	readyCalls: decimal({ precision: 15, scale: 2 }),
	launchCalls: decimal({ precision: 15, scale: 2 }),
	avgReceiptTime: decimal({ precision: 10, scale: 2 }),
	cancelledPendingRatio: decimal({ precision: 5, scale: 2 }),
	avgSaleTime: decimal({ precision: 10, scale: 2 }),
	avgPropertyValue: decimal({ precision: 15, scale: 2 }),
	networkBusiness: decimal({ precision: 15, scale: 2 }),
	internalBusiness: decimal({ precision: 15, scale: 2 }),
	externalPartnership: decimal({ precision: 15, scale: 2 }),
	launchBusiness: decimal({ precision: 15, scale: 2 }),
	generalExpense: decimal({ precision: 15, scale: 2 }),
	taxExpense: decimal({ precision: 15, scale: 2 }),
	innovationFund: decimal({ precision: 15, scale: 2 }),
	partnersResult: decimal({ precision: 15, scale: 2 }),
	emergencyFund: decimal({ precision: 15, scale: 2 }),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP'),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow(),
});

export const historicalSales = mysqlTable("historicalSales", {
	id: varchar({ length: 64 }).notNull(),
	companyId: varchar({ length: 64 }).notNull(),
	propertyReference: varchar({ length: 100 }),
	propertyAddress: text(),
	propertyNeighborhood: varchar({ length: 255 }),
	businessType: varchar({ length: 100 }),
	saleDate: timestamp({ mode: 'string' }),
	acquisitionDate: timestamp({ mode: 'string' }),
	listingPrice: decimal({ precision: 15, scale: 2 }),
	salePrice: decimal({ precision: 15, scale: 2 }),
	commissionAmount: decimal({ precision: 15, scale: 2 }),
	commissionPercentage: decimal({ precision: 5, scale: 2 }),
	acquisitionBrokerName: varchar({ length: 255 }),
	saleBrokerName: varchar({ length: 255 }),
	acquisitionStore: varchar({ length: 100 }),
	saleStore: varchar({ length: 100 }),
	clientSource: varchar({ length: 255 }),
	paymentMethod: varchar({ length: 255 }),
	status: varchar({ length: 50 }).default('commission_paid'),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP'),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow(),
});

export const indicatorDetails = mysqlTable("indicatorDetails", {
	id: varchar({ length: 64 }).notNull(),
	snapshotId: varchar({ length: 64 }).notNull(),
	indicatorName: varchar({ length: 100 }).notNull(),
	entityType: varchar({ length: 50 }).notNull(),
	entityIds: text().notNull(),
	calculationDetails: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP'),
});

export const indicatorGoals = mysqlTable("indicatorGoals", {
	id: varchar({ length: 64 }).notNull(),
	companyId: varchar({ length: 64 }).notNull(),
	indicatorName: varchar({ length: 100 }).notNull(),
	year: int().notNull(),
	monthlyGoal: decimal({ precision: 15, scale: 2 }),
	annualAverage: decimal({ precision: 15, scale: 2 }),
	createdBy: varchar({ length: 64 }).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP'),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow(),
});

export const models = mysqlTable("models", {
	id: varchar({ length: 64 }).notNull(),
	companyId: varchar({ length: 64 }),
	modelType: mysqlEnum(['paymentMethod','clientOrigin','carteiraSituation','teamType','rejectionReason','businessType']).notNull(),
	name: varchar({ length: 255 }).notNull(),
	description: text(),
	isDefault: tinyint().default(0),
	isActive: tinyint().default(1),
	createdBy: varchar({ length: 64 }).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP'),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow(),
});

export const monthlyIndicators = mysqlTable("monthlyIndicators", {
	id: varchar({ length: 64 }).notNull(),
	month: varchar({ length: 7 }).notNull(),
	companyId: varchar({ length: 64 }).notNull(),
	generalExpense: decimal({ precision: 15, scale: 2 }),
	taxExpense: decimal({ precision: 15, scale: 2 }),
	innovationFund: decimal({ precision: 15, scale: 2 }),
	partnerResult: decimal({ precision: 15, scale: 2 }),
	emergencyFund: decimal({ precision: 15, scale: 2 }),
	createdBy: varchar({ length: 64 }).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP'),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow(),
});

export const monthlyIndicatorsSnapshot = mysqlTable("monthlyIndicatorsSnapshot", {
	id: varchar({ length: 64 }).notNull(),
	companyId: varchar({ length: 64 }).notNull(),
	month: varchar({ length: 7 }).notNull(),
	year: int().notNull(),
	monthNumber: int().notNull(),
	salesValueMonth: decimal({ precision: 15, scale: 2 }),
	salesCountMonth: int(),
	cancelledSalesCount: int(),
	commissionReceived: decimal({ precision: 15, scale: 2 }),
	commissionSold: decimal({ precision: 15, scale: 2 }),
	commissionPendingEndMonth: decimal({ precision: 15, scale: 2 }),
	percentCommissionSold: decimal({ precision: 5, scale: 2 }),
	salesAbove1M: int(),
	avgPaymentDays: decimal({ precision: 10, scale: 2 }),
	percentCancelledVsPending: decimal({ precision: 5, scale: 2 }),
	avgSaleTime: decimal({ precision: 10, scale: 2 }),
	avgPropertyValue: decimal({ precision: 15, scale: 2 }),
	salesUna: int(),
	salesInternal: int(),
	salesExternalPartner: int(),
	salesLaunch: int(),
	activePropertiesCount: int(),
	angariationsCount: int(),
	removedPropertiesCount: int(),
	leadsReadyCount: int(),
	leadsLaunchCount: int(),
	vso: decimal({ precision: 5, scale: 2 }),
	generalExpense: decimal({ precision: 15, scale: 2 }),
	taxExpense: decimal({ precision: 15, scale: 2 }),
	innovationFund: decimal({ precision: 15, scale: 2 }),
	partnerResult: decimal({ precision: 15, scale: 2 }),
	emergencyFund: decimal({ precision: 15, scale: 2 }),
	isClosed: tinyint().default(0),
	closedAt: timestamp({ mode: 'string' }),
	closedBy: varchar({ length: 64 }),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP'),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow(),
});

export const properfyLeads = mysqlTable("properfyLeads", {
	id: varchar({ length: 64 }).notNull(),
	propertyId: varchar({ length: 64 }),
	leadId: varchar({ length: 64 }).notNull(),
	leadName: varchar({ length: 255 }),
	leadEmail: varchar({ length: 320 }),
	leadPhone: varchar({ length: 20 }),
	leadType: mysqlEnum(['ready','launch','other']).default('other'),
	status: varchar({ length: 64 }).default('active'),
	createdAt: timestamp({ mode: 'string' }),
	updatedAt: timestamp({ mode: 'string' }),
	syncedAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP'),
});

export const properfyProperties = mysqlTable("properfyProperties", {
	id: int().notNull(),
	chrReference: varchar({ length: 100 }).notNull(),
	chrInnerReference: varchar({ length: 100 }),
	chrType: varchar({ length: 50 }),
	chrStatus: varchar({ length: 50 }),
	chrTransactionType: varchar({ length: 50 }),
	dcmAreaTotal: decimal({ precision: 10, scale: 2 }),
	dcmAreaPrivate: decimal({ precision: 10, scale: 2 }),
	dcmAreaUsable: decimal({ precision: 10, scale: 2 }),
	dcmAreaBuilt: decimal({ precision: 10, scale: 2 }),
	intRooms: int(),
	intBedrooms: int(),
	intSuites: int(),
	intBathrooms: int(),
	intGarage: int(),
	dcmSale: decimal({ precision: 15, scale: 2 }),
	dcmRentNetValue: decimal({ precision: 15, scale: 2 }),
	dcmCondoValue: decimal({ precision: 15, scale: 2 }),
	dcmPropertyTax: decimal({ precision: 15, scale: 2 }),
	chrAddressPostalCode: varchar({ length: 20 }),
	chrAddressStreet: text(),
	chrAddressNumber: varchar({ length: 20 }),
	chrAddressComplement: varchar({ length: 255 }),
	chrAddressNeighborhood: varchar({ length: 255 }),
	chrAddressCity: varchar({ length: 255 }),
	chrAddressCityCode: varchar({ length: 20 }),
	chrAddressState: varchar({ length: 2 }),
	chrCondoName: varchar({ length: 255 }),
	fkCondo: int(),
	intBuiltYear: int(),
	intFloors: int(),
	companyId: varchar({ length: 64 }),
	lastSyncedAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP'),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP'),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow(),
	isActive: int().default(0),
	chrPurpose: varchar({ length: 100 }),
	dteNewListing: timestamp({ mode: 'string' }),
	dteTermination: timestamp({ mode: 'string' }),
},
(table) => [
	index("idx_properfy_reference").on(table.chrReference),
	index("idx_properfy_postal_code").on(table.chrAddressPostalCode),
	index("idx_properfy_city_code").on(table.chrAddressCityCode),
	index("idx_chrReference").on(table.chrReference),
]);

export const properties = mysqlTable("properties", {
	id: varchar({ length: 64 }).notNull(),
	companyId: varchar({ length: 64 }).notNull(),
	propertyReference: varchar({ length: 64 }),
	isFromBaggio: tinyint().default(0),
	address: text().notNull(),
	zipCode: varchar({ length: 10 }),
	neighborhood: varchar({ length: 255 }),
	city: varchar({ length: 255 }),
	state: varchar({ length: 2 }),
	number: varchar({ length: 20 }),
	complement: text(),
	advertisementValue: decimal({ precision: 15, scale: 2 }),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP'),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow(),
});

export const propertiesCache = mysqlTable("propertiesCache", {
	id: varchar({ length: 64 }).notNull(),
	companyId: varchar({ length: 64 }).notNull(),
	properfyId: varchar({ length: 64 }).notNull(),
	chrReference: varchar({ length: 255 }),
	chrDocument: varchar({ length: 255 }),
	chrStatus: varchar({ length: 50 }),
	dteNewListing: timestamp({ mode: 'string' }),
	dteTermination: timestamp({ mode: 'string' }),
	chrTerminationReason: varchar({ length: 255 }),
	propertyType: varchar({ length: 50 }),
	saleValue: decimal({ precision: 15, scale: 2 }),
	lastSyncAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP'),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP'),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow(),
});

export const propertyHistory = mysqlTable("propertyHistory", {
	id: varchar({ length: 64 }).notNull(),
	companyId: varchar({ length: 64 }).notNull(),
	propertyReference: varchar({ length: 64 }).notNull(),
	previousValue: decimal({ precision: 15, scale: 2 }),
	newValue: decimal({ precision: 15, scale: 2 }),
	previousStatus: varchar({ length: 255 }),
	newStatus: varchar({ length: 255 }),
	reason: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP'),
});

export const proposalComments = mysqlTable("proposalComments", {
	id: varchar({ length: 64 }).notNull(),
	saleId: varchar({ length: 64 }).notNull(),
	companyId: varchar({ length: 64 }).notNull(),
	userId: varchar({ length: 64 }).notNull(),
	userName: varchar({ length: 255 }),
	previousStatus: varchar({ length: 50 }),
	newStatus: varchar({ length: 50 }),
	comment: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP'),
});

export const proposals = mysqlTable("proposals", {
	id: varchar({ length: 64 }).notNull(),
	companyId: varchar({ length: 64 }).notNull(),
	propertyReference: varchar({ length: 64 }).notNull(),
	brokerAngariadorId: varchar({ length: 64 }).notNull(),
	status: mysqlEnum(['proposta','vendido','recusado','outro']).default('proposta').notNull(),
	customStatus: varchar({ length: 255 }),
	rejectionReason: varchar({ length: 255 }),
	rejectionDate: timestamp({ mode: 'string' }),
	rejectionObservation: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP'),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow(),
});

export const salePaymentHistory = mysqlTable("salePaymentHistory", {
	id: varchar({ length: 64 }).notNull(),
	saleId: varchar({ length: 64 }).notNull(),
	fieldChanged: varchar({ length: 100 }).notNull(),
	oldValue: text(),
	newValue: text().notNull(),
	changedBy: varchar({ length: 64 }).notNull(),
	changedByName: varchar({ length: 255 }),
	reason: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP'),
});

export const sales = mysqlTable("sales", {
	id: varchar({ length: 64 }).notNull(),
	companyId: varchar({ length: 64 }).notNull(),
	propertyId: varchar({ length: 64 }).notNull(),
	buyerName: varchar({ length: 255 }).notNull(),
	buyerCpfCnpj: varchar({ length: 20 }),
	saleDate: timestamp({ mode: 'string' }),
	angariationDate: timestamp({ mode: 'string' }),
	saleValue: decimal({ precision: 15, scale: 2 }).notNull(),
	clientOrigin: varchar({ length: 255 }),
	paymentMethod: varchar({ length: 255 }),
	brokerAngariador: varchar({ length: 64 }),
	brokerVendedor: varchar({ length: 64 }),
	businessType: varchar({ length: 255 }),
	status: mysqlEnum(['draft','pending','sale','manager_review','finance_review','commission_paid','cancelled']).default('draft').notNull(),
	observation: text(),
	proposalDocumentUrl: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP'),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow(),
	propertyType: varchar({ length: 255 }),
	bedrooms: int(),
	costPerM2: decimal({ precision: 15, scale: 2 }),
	privateArea: decimal({ precision: 10, scale: 2 }),
	totalArea: decimal({ precision: 10, scale: 2 }),
	propertyAge: int(),
	investmentType: varchar({ length: 255 }),
	financedValue: decimal({ precision: 15, scale: 2 }),
	cartoryBank: varchar({ length: 255 }),
	despachante: varchar({ length: 255 }),
	sellerName: varchar({ length: 255 }),
	sellerCpfCnpj: varchar({ length: 20 }),
	sellerPhone: varchar({ length: 20 }),
	buyerPhone: varchar({ length: 20 }),
	condominiumName: varchar({ length: 255 }),
	advertisementValue: decimal({ precision: 15, scale: 2 }),
	totalCommission: decimal({ precision: 15, scale: 2 }),
	totalCommissionPercent: decimal({ precision: 5, scale: 2 }),
	angariadorCommission: decimal({ precision: 15, scale: 2 }),
	vendedorCommission: decimal({ precision: 15, scale: 2 }),
	baggioCommission: decimal({ precision: 15, scale: 2 }),
	expectedPaymentDate: timestamp({ mode: 'string' }),
	brokerAngariadorType: mysqlEnum(['internal','external']).default('internal'),
	brokerAngariadorName: varchar({ length: 255 }),
	brokerAngariadorCreci: varchar({ length: 50 }),
	brokerAngariadorEmail: varchar({ length: 320 }),
	brokerVendedorType: mysqlEnum(['internal','external']).default('internal'),
	brokerVendedorName: varchar({ length: 255 }),
	brokerVendedorCreci: varchar({ length: 50 }),
	brokerVendedorEmail: varchar({ length: 320 }),
	registeredBy: varchar({ length: 64 }),
	registeredByName: varchar({ length: 255 }),
	registeredAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP'),
	realEstateCommission: decimal({ precision: 15, scale: 2 }),
	saleType: mysqlEnum(['lancamento','pronto']),
	responsible: varchar({ length: 255 }),
	invoiceNumber: varchar({ length: 100 }),
	listingDate: timestamp({ mode: 'string' }),
	listingStore: varchar({ length: 100 }),
	sellingStore: varchar({ length: 100 }),
	team: varchar({ length: 100 }),
	region: varchar({ length: 100 }),
	managementResponsible: varchar({ length: 100 }),
	deedStatus: varchar({ length: 50 }),
	bankName: varchar({ length: 255 }),
	financedAmount: decimal({ precision: 15, scale: 2 }),
	bankReturnPercentage: decimal({ precision: 5, scale: 2 }),
	bankReturnAmount: decimal({ precision: 15, scale: 2 }),
	observations: text(),
	wasRemoved: tinyint().default(0),
	priceDiscount: decimal({ precision: 15, scale: 2 }),
	listingToSaleDays: int(),
	commissionPaymentDate: timestamp({ mode: 'string' }),
	commissionAmountReceived: decimal({ precision: 15, scale: 2 }),
	commissionPaymentBank: varchar({ length: 255 }),
	commissionPaymentMethod: varchar({ length: 100 }),
	commissionPaymentObservations: text(),
	downPaymentPercentage: decimal({ precision: 5, scale: 2 }),
	contractNumber: varchar({ length: 100 }),
	contractSignatureDate: timestamp({ mode: 'string' }),
	portfolioStatus: varchar({ length: 100 }),
	tipoComissao: mysqlEnum(['Venda Interna','Parceria UNA','Parceria Externa','Lançamento']),
	porcentagemComissao: decimal({ precision: 5, scale: 2 }),
	comissaoTotal: decimal({ precision: 15, scale: 2 }),
	comissaoAngariador: decimal({ precision: 15, scale: 2 }),
	comissaoCoordenador: decimal({ precision: 15, scale: 2 }),
	comissaoVendedor: decimal({ precision: 15, scale: 2 }),
	comissaoImobiliaria: decimal({ precision: 15, scale: 2 }),
	comissaoParceira: decimal({ precision: 15, scale: 2 }),
	comissaoAutonomo: decimal({ precision: 15, scale: 2 }),
	possuiBonificacao: tinyint().default(0),
	tipoBonificacao: mysqlEnum(['Dinheiro','Material']),
	valorBonificacao: decimal({ precision: 15, scale: 2 }),
	descricaoBonificacao: text(),
	comissaoBonificacaoCorretor: decimal({ precision: 15, scale: 2 }),
	comissaoBonificacaoImobiliaria: decimal({ precision: 15, scale: 2 }),
	sinalNegocio: mysqlEnum(['Baggio','Outra']),
	sinalNegocioEmpresa: varchar({ length: 255 }),
	sinalNegocioValor: decimal({ precision: 15, scale: 2 }),
	sinalNegocioDataPagamento: timestamp({ mode: 'string' }),
	sinalNegocioComprovanteUrl: text(),
	documents: text(),
});

export const salesHistory = mysqlTable("salesHistory", {
	id: varchar({ length: 64 }).notNull(),
	saleId: varchar({ length: 64 }).notNull(),
	companyId: varchar({ length: 64 }).notNull(),
	changedBy: varchar({ length: 64 }).notNull(),
	changedByName: varchar({ length: 255 }),
	action: mysqlEnum(['create','update','delete','status_change','approval','rejection']).notNull(),
	fieldName: varchar({ length: 100 }),
	previousValue: text(),
	newValue: text(),
	changeReason: text(),
	ipAddress: varchar({ length: 45 }),
	userAgent: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP'),
});

export const users = mysqlTable("users", {
	id: varchar({ length: 64 }).notNull(),
	name: text(),
	email: varchar({ length: 320 }),
	loginMethod: varchar({ length: 64 }).default('email'),
	role: mysqlEnum(['superadmin','admin','manager','broker','finance','viewer']).default('broker').notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP'),
	lastSignedIn: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP'),
	password: text(),
	companyId: varchar({ length: 64 }),
	isActive: tinyint().default(1),
	failedLoginAttempts: int().default(0),
	lockedUntil: timestamp({ mode: 'string' }),
	resetToken: varchar({ length: 128 }),
	resetTokenExpiry: timestamp({ mode: 'string' }),
	managerId: varchar({ length: 64 }),
},
(table) => [
	index("users_email_unique").on(table.email),
]);
